name: 'vendas_carros_noruega'
version: '1.0.0'

profile: 'vendas_carros_noruega'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  vendas_carros_noruega:
    staging:
      schema: staging
      materialized: view
      tags: ['staging']

    intermediate:
      materialized: ephemeral
      tags: ['intermediate']

    marts:
      schema: marts
      materialized: table
      tags: ['marts']

seeds:
  vendas_carros_noruega:
    +schema: raw
    tags: ['seeds']

snapshots:
  vendas_carros_noruega:
    tags: ['snapshots']
    schema: snapshots
